version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/ssl:/etc/nginx/ssl:ro
    networks:
      - stuco-net
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./back-end
      dockerfile: ../docker/backend.Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    networks:
      - stuco-net
    restart: unless-stopped

  email-service:
    build:
      context: ./email-service
      dockerfile: ../docker/email-service.Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    networks:
      - stuco-net
    restart: unless-stopped

networks:
  stuco-net:
