version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - stuco-net
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./back-end
      dockerfile: ../docker/backend.Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - stuco-net
    restart: unless-stopped

  email-service:
    build:
      context: ./email-service
      dockerfile: ../docker/email-service.Dockerfile
    networks:
      - stuco-net
    restart: unless-stopped

networks:
  stuco-net: