version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "80:80"
    networks:
      - stuco-net

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - stuco-net

  email-service:
    build:
      context: .
      dockerfile: docker/email-service.Dockerfile
    ports:
      - "8081:8081"
    networks:
      - stuco-net

networks:
  stuco-net: