version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "5173:5173"
    networks:
      - stuco-net
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - stuco-net
    restart: unless-stopped

  email-service:
    build:
      context: .
      dockerfile: docker/email-service.Dockerfile
    ports:
      - "8081:8081"
    networks:
      - stuco-net
    restart: unless-stopped

networks:
  stuco-net: